// /robots.txt servido dinamicamente. Permite a buscadores y a bots de LLMs.
// Bloquea solo /api/ (excepto endpoints publicos como sitemap/robots/llms).
const BASE_URL = 'https://capitaldepas.com';

module.exports = (req, res) => {
  const lines = [
    '# capitaldepas.com - robots.txt',
    '# Permitimos a buscadores tradicionales y a bots de IA/LLMs.',
    '# Para excluirlos, descomenta las lineas "Disallow: /" correspondientes.',
    '',
    '# --- Buscadores tradicionales ---',
    'User-agent: Googlebot',
    'Allow: /',
    '',
    'User-agent: Googlebot-Image',
    'Allow: /',
    '',
    'User-agent: Bingbot',
    'Allow: /',
    '',
    'User-agent: DuckDuckBot',
    'Allow: /',
    '',
    'User-agent: Applebot',
    'Allow: /',
    '',
    'User-agent: YandexBot',
    'Allow: /',
    '',
    'User-agent: Baiduspider',
    'Allow: /',
    '',
    '# --- Bots de IA / LLMs (entrenamiento + answer engines) ---',
    'User-agent: GPTBot',
    'Allow: /',
    '',
    'User-agent: ChatGPT-User',
    'Allow: /',
    '',
    'User-agent: OAI-SearchBot',
    'Allow: /',
    '',
    'User-agent: ClaudeBot',
    'Allow: /',
    '',
    'User-agent: Claude-Web',
    'Allow: /',
    '',
    'User-agent: anthropic-ai',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    'User-agent: Perplexity-User',
    'Allow: /',
    '',
    'User-agent: Google-Extended',
    'Allow: /',
    '',
    'User-agent: GoogleOther',
    'Allow: /',
    '',
    'User-agent: CCBot',
    'Allow: /',
    '',
    'User-agent: Bytespider',
    'Allow: /',
    '',
    'User-agent: Meta-ExternalAgent',
    'Allow: /',
    '',
    'User-agent: Meta-ExternalFetcher',
    'Allow: /',
    '',
    'User-agent: FacebookBot',
    'Allow: /',
    '',
    'User-agent: Amazonbot',
    'Allow: /',
    '',
    'User-agent: Cohere-AI',
    'Allow: /',
    '',
    'User-agent: Diffbot',
    'Allow: /',
    '',
    '# --- Reglas globales ---',
    'User-agent: *',
    'Allow: /',
    'Disallow: /api/',
    'Allow: /api/sitemap',
    'Allow: /api/robots',
    'Allow: /api/llms',
    'Allow: /api/config',
    '',
    'Sitemap: ' + BASE_URL + '/sitemap.xml',
    'Host: ' + BASE_URL.replace(/^https?:\/\//, ''),
  ];
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate=604800');
  res.status(200).send(lines.join('\n'));
};
